apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "terminator.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list