{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "terminator.fullname" . }}-docker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminator.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}