# Default values for terminator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: fireflycons/terminator
  pullPolicy: IfNotPresent

args: []

imageCredentials: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


resources:
  limits:
    cpu: 50m
    memory: 96Mi
  requests:
    cpu: 50m
    memory: 96Mi


nodeSelector: {}

tolerations: []

affinity: {}
